library(tidyverse)
library(rgrass7)
library(sf)
message('Hi!')
message(getwd())
system('whoami')
writeLines('Yo!', 'docker-mount/test.txt')

writeLines('Yo!', 'docker-mount/yeehaw.txt')
link = link2GI::findGRASS()
print(link)
#system2("find", "/usr ! -readable -prune -o -type f -executable -iname 'grass??' -print")
#initGRASS(gisBase = "/usr/share")