validation_targets <-
  list(
    tar_target(
      nhdplus_lines,
      read_nhd_lines(FILEPATH_NHDPLUS)
    ),
    tar_target(
      nhdplus_coastline,
      read_nhd_coastline(FILEPATH_NHDPLUS)
    ),
    tar_target(
      nhdplus_coastline_contiguous,
      make_coastline_clean(nhdplus_coastline)
    ),
    tar_target(
      nhdplus_hortonmerge,
      linemerge_ala_horton(nhdplus_lines)
    ),
    tar_target(
      catchments_contiguous_us,
      read_nhd_studyarea(FILEPATH_NHDPLUS)
    ),
    tar_target(
      contiguous_us_single_polygon,
      union_nhd_studyarea_in_db(
        catchments_contiguous_us,
        VALIDATION_STUDYAREA
      )
    ),
    tar_target(
      studyarea_validation,
      contiguous_us_single_polygon %>%
        adaptor_studyarea_validation()
    ),
    tar_target(
      watershed_validation,
      studyarea_validation %>%
        make_watershed_boundary(nhdplus_coastline_contiguous)
    ),
    tar_target(
      waterbodies_validation,
      read_waterbodies_validation(FILEPATH_NHDPLUS)
    ),
    tar_target(
      water_bodies_validation_intersected,
      filter_intersecting_waterbodies(
        waterbodies_validation,
        nhdplus_hortonmerge
      )
    ),
    tar_target(
      waterbodies_plus,
      waterbodies_add_riverid(
        water_bodies_validation_intersected,
        nhdplus_hortonmerge
      )
    ),
    tar_target(
      usmohp_reproduction_data,
      calculate_mohp_metrics_in_grassdb_validation(
        nhdplus_hortonmerge,
        NULL,
        studyarea_validation,
        7,
        nhdplus_coastline_contiguous
      ),
      deployment = "main"
    ),
    tar_target(
      sampling_area,
      studyarea_validation %>%
        st_buffer(BUFFER_SAMPLING_AREA)
    ),
    tar_target(
      sampling_points,
      sampling_area %>%
        st_sample(size = SAMPLING_SIZE) %>% 
        st_as_sf()
    ),
    tar_target(
      plot_validation_sampling,
      make_validation_sampling_plot(
        studyarea_validation,
        sampling_area,
        sampling_points
      )
    ),
    tar_target(
      lp7_original,
      read_stars(FILEPATH_LP7_ORIGINAL, proxy = TRUE)
    ),
    tar_target(
      lp7_reproduced,
      read_lp7_reproduced(
        FILEPATH_LP7_REPRODUCED, 
        lp7_original,
        depends_on = usmohp_reproduction_data
        )
    ),
    tar_target(
      raster_difference,
      make_raster_difference(
        lp7_original,
        lp7_reproduced
      )
    ),
    tar_target(
      raster_difference_perc,
      make_raster_difference(
        lp7_original,
        lp7_reproduced,
        as_percentage = TRUE
      )
    ),
    tar_target(
      raster_difference_plot,
      make_raster_difference_plot(
        raster_difference
      )
    ),
    tar_target(
      raster_difference_perc_plot,
      make_raster_difference_perc_plot(
        raster_difference_perc
      )
    ),
    tar_target(
      raster_values_original,
      extract_raster_values(
        lp7_original,
        sampling_points,
        "original"
      )
    ),
    tar_target(
      raster_values_reproduced,
      extract_raster_values(
        lp7_reproduced,
        sampling_points,
        "reproduced"
      )
    ),
    tar_target(
      lm_plot,
      make_lm_plot(
        raster_values_original,
        raster_values_reproduced
      )
    )
  )